---
  "sat_style":
    "sat":
      "marker": "x"
      "color": "purple"
      "label": "SAT"
    "unsat":
      "marker": "o"
      "color": "black"
      "label": "UNSAT"
    "unsolved":
      "marker": "+"
      "color": "red"
      "label": "UNSOLVED"