---
  markers:
    - - o
      - true
    - x
    - - s
      - true
  colors:
    - purple
    - black
    - blue
  # "sat_style":
  #   "sat":
  #     "marker": "x"
  #     "color": "purple"
  #     "label": "SAT"
  #   "unsat":
  #     "marker": "o"
  #     "color": "black"
  #     "label": "UNSAT"
  #   "unsolved":
  #     "marker": "+"
  #     "color": "blue"
  #     "label": "UNSOLVED"
  "solver_style":
    "c24":
      "label": "Cadical24"
    "c25":
      "label": "Cadical25"
    "k24":
      "label": "Kissat24"
  "indicator_lines":
    - "axline_args": 
      - [0.0, 0.0]
      - [10.0, 100.0]
      "axline_kwargs":
        "color": "#C9B800"
        "zorder": 0
    - "axline_args": 
      - [0.0, 0.0]
      - [10.0, 20.0]
      "axline_kwargs":
        "color": "#996515"
        "zorder": 0
    - "axline_args": 
      - [0.0, 0.0]
      - [10.0, 10.0]
      "axline_kwargs":
        "color": "#00A88A"
        "zorder": 0
    - "axline_args": 
      - [0.0, 0.0]
      - [10.0, 5.0]
      "axline_kwargs":
        "color": "#3FA0FF"
        "zorder": 0
    - "axline_args": 
      - [0.0, 0.0]
      - [10.0, 1.0]
      "axline_kwargs":
        "color": "#7FCBFF"
        "zorder": 0
  "grid_kwargs":
    "which": "major"
    "color": "gray"
    "linestyle": ":"
    "linewidth": 0.7
    "alpha": 0.7
