cactus: false
center: true
colors:
- '#9400d3'
- '#009e73'
- '#56b4e9'
- '#e69f00'
- '#f0e442'
- '#0072b2'
- '#e51e10'
- '#000000'
font_family: serif
grid: false
hollow: false
latex: true
latex_preamble: '\usepackage{lmodern}'
legend_kwargs:
  fontsize: 8
  markerscale: 1.0
  edgecolor: 'black'
  framealpha: 1.0
  fancybox: false
limit: null
line_segments: false
lines: false
markers:
- .
- ^
- +
- x
- d
output: learn_to_unlearn_fig10.pdf
plain: false
show_solved: true
subplots_kwargs:
  figsize:
  - 7
  - 8
title: null
xlabel: null
xlegend: null
xlog: false
xmax: 9500.0
xmin: null
y_major_ticks:
- 260.0
- 280.0
- 300.0
- 320.0
y_tick_kwargs:
  pad: 6
y_tick_rotation: 90
ylabel: null
ylegend: null
ylog: false
ymax: 335.0
ymin: 245.0