create_solver_style: true
colors:
- "#000000"
- "#df526b"
- "#9e9e9e"
- "#f5c610"
- "#2196e6"
markers:
- - o
  - true
- x
- - s
  - true
- - d
  - true
- +
- - ^
  - true
- - v
  - true
- - p
  - true
- - '*'
  - true
- o
- s
- ^
- v
- p
universal_solver_style:
  markersize: 5
specific_solver_style:
  4.0.2:
    label: competition
  4.0.2-cr-base-1-no-reduce:
    label: "no\u2212unlearn"
  4.0.2-cr-base-2:
    label: base
  4.0.2-cr-base-2-activity:
    label: activity
  4.0.2-cr-base-2-activity+used:
    label: activity + used
  4.0.2-cr-base-2-keep-dynamic2:
    label: critical@lbd\textless=dynamic
  4.0.2-cr-base-2-keep-dynamic2+used:
    label: critical@lbd\textless=dynamic + used
  4.0.2-cr-base-2-keep-dynamic2-size:
    label: critical@size\textless=dynamic
  4.0.2-cr-base-2-keep-dynamic2-size+used:
    label: critical@size\textless=dynamic + used
  4.0.2-cr-base-2-keep-glue1:
    label: critical@lbd\textless=1
  4.0.2-cr-base-2-keep-glue2:
    label: critical@lbd\textless=2
  4.0.2-cr-base-2-keep-glue2+used:
    label: critical@lbd\textless=2 + used
  4.0.2-cr-base-2-keep-glue2-reducetarget=75:
    label: critical@lbd\textless=2 + rank@lbd=75%
  4.0.2-cr-base-2-keep-glue3:
    label: critical@lbd\textless=3
  4.0.2-cr-base-2-keep-glue3+used:
    label: critical@lbd\textless=3 + used
  4.0.2-cr-base-2-keep-glue3+used2:
    label: critical@lbd\textless=3 + used + anotherchance
  4.0.2-cr-base-2-keep-glue3-reducetarget=75:
    label: critical@lbd\textless=3 + rank@lbd=75%
  4.0.2-cr-base-2-keep-glue4:
    label: critical@lbd\textless=4
  4.0.2-cr-base-2-keep-glue5:
    label: critical@lbd\textless=5
  4.0.2-cr-base-2-keep-glue6:
    label: critical@lbd\textless=6
  4.0.2-cr-base-2-keep-glue7:
    label: critical@lbd\textless=7
  4.0.2-cr-base-2-keep-size10:
    label: critical@size\textless=10
  4.0.2-cr-base-2-keep-size10+used:
    label: critical@size\textless=10 + used
  4.0.2-cr-base-2-keep-size10+used2:
    label: critical@size\textless=10 + used + anotherchance
  4.0.2-cr-base-2-keep-size10-reducetarget=75:
    label: critical@size\textless=10 + rank@size=75%
  4.0.2-cr-base-2-keep-size15:
    label: critical@size\textless=15
  4.0.2-cr-base-2-keep-size21:
    label: critical@size\textless=21
  4.0.2-cr-base-2-keep-size3:
    label: critical@size\textless=3
  4.0.2-cr-base-2-keep-size6:
    label: critical@size\textless=6
  4.0.2-cr-base-2-keep-size6+used:
    label: critical@size\textless=6 + used
  4.0.2-cr-base-2-keep-size6+used-reducetarget=75:
    label: critical@size\textless=6 + rank@size=75% + used
  4.0.2-cr-base-2-keep-size6-reducetarget=75:
    label: critical@size\textless=6 + rank@size=75%
  4.0.2-cr-base-2-keep-used:
    label: used
  4.0.2-cr-base-2-keep-used2:
    label: used + anotherchance
  4.0.2-cr-base-2-rank-glue:
    label: rank@lbd=50%
  4.0.2-cr-base-2-rank-glue+used:
    label: rank@lbd=50% + used
  4.0.2-cr-base-2-rank-glue+used-reducetarget=75:
    label: rank@lbd=75% + used
  4.0.2-cr-base-2-rank-glue-reducetarget=75:
    label: rank@lbd=75%
  4.0.2-cr-base-2-rank-size:
    label: rank@size=50%
  4.0.2-cr-base-2-rank-size+used:
    label: rank@size=50% + used
  4.0.2-cr-base-2-rank-size+used-reducetarget=75:
    label: rank@size=75% + used
  4.0.2-cr-base-2-rank-size-reducetarget=75:
    label: rank@size=75%
  4.0.2-cr-base-2-reduce-all:
    label: unlearn-all
